### ISSUE TITLE
Add information on how to run Raiden on testnets

### ISSUE THREAD

**Issue by czepluch** [raiden-network/raiden-documentation#12]
I think it would be nice to have a dedicated part where we explain how people can run Raiden on testnets for testing purposes. I get this questions quite a lot during the current gitcoin hackathon for instance.

**Comment by manuelwedler** [comment]
I will add a docs page on how to use the Wizard to run Raiden on Goerli.

**Comment by manuelwedler** [comment]
The [Quick Start on Görli](https://docs.raiden.network/using-raiden-on-testnet/quick-start-on-goerli-testnet) page is live!

**Comment by czepluch** [comment]
Great. Thanks a lot.
